# Generated by Django 4.0.4 on 2022-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_address', models.CharField(max_length=255)),
                ('s_age', models.IntegerField()),
                ('s_gender', models.CharField(max_length=255)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_jdate', models.DateField()),
                ('s_qualification', models.CharField(max_length=255)),
                ('s_pno', models.IntegerField()),
            ],
        ),
    ]
